# model.py
# Threat classifier for SENTINEL
# Trains a RandomForest on synthetic data generated by the simulation engine,
# then scores live entities with a threat_score, confidence, and
# feature importance breakdown.

import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import classification_report
import random

from backend.simulation.engine import (
    Entity, EntityType, spawn_entity, attach_intel_report
)


# ── Feature Extraction ────────────────────────────────────────────────────────
# Converts an Entity into a flat feature vector the classifier can consume.
# Only structured numerical features are used here — the LLM handles
# the natural language reasoning separately.

FEATURE_NAMES = [
    "speed",
    "distance_to_hostile_zone",
    "pattern_of_life_deviation",
    "signal_count",
    "max_signal_value",
    "mean_signal_value",
    "has_encrypted_comms",
    "has_thermal_spike",
    "has_weapons_profile",
    "has_erratic_movement",
    "has_blufor_transponder",
    "has_civilian_signal",
    "has_ambiguous_signal",
]


def extract_features(entity: Entity) -> np.ndarray:
    """
    Extract a fixed-length feature vector from an entity.
    This is what the classifier sees — no labels, no ground truth.
    """
    signal_types  = {se.signal_type for se in entity.sensor_events}
    signal_values = [se.value for se in entity.sensor_events]

    civilian_signals  = {"mobile_signal", "foot_traffic", "market_activity", "vehicle_idle"}
    ambiguous_signals = {"unencrypted_comms", "unusual_movement", "unknown_vehicle", "nighttime_activity"}

    features = [
        entity.speed,
        entity.distance_to_hostile_zone,
        entity.pattern_of_life_deviation,
        len(entity.sensor_events),                              # signal_count
        max(signal_values) if signal_values else 0.0,           # max_signal_value
        sum(signal_values) / len(signal_values) if signal_values else 0.0,  # mean_signal_value
        1.0 if "encrypted_comms"   in signal_types else 0.0,   # has_encrypted_comms
        1.0 if "thermal_spike"     in signal_types else 0.0,   # has_thermal_spike
        1.0 if "weapons_profile"   in signal_types else 0.0,   # has_weapons_profile
        1.0 if "erratic_movement"  in signal_types else 0.0,   # has_erratic_movement
        1.0 if "blufor_transponder" in signal_types else 0.0,  # has_blufor_transponder
        1.0 if signal_types & civilian_signals else 0.0,        # has_civilian_signal
        1.0 if signal_types & ambiguous_signals else 0.0,       # has_ambiguous_signal
    ]

    return np.array(features, dtype=np.float32)


# ── Synthetic Training Data Generator ────────────────────────────────────────
# Generates a large batch of labeled entities using the simulation engine.
# This is our training set — the classifier learns the statistical fingerprints
# we defined in the spawner.

def generate_training_data(n_samples: int = 2000) -> tuple[np.ndarray, np.ndarray]:
    """
    Spawn n_samples entities across all types, extract features, and
    return (X, y) arrays ready for sklearn training.

    Labels:
        0 = non-threat  (civilian, friendly)
        1 = threat      (hostile)
        2 = uncertain   (ambiguous)
    """
    X, y = [], []

    # Balance the dataset — equal samples per type
    per_type = n_samples // 4

    label_map = {
        EntityType.CIVILIAN:  0,
        EntityType.FRIENDLY:  0,   # Friendlies are non-threats
        EntityType.HOSTILE:   1,
        EntityType.AMBIGUOUS: 2,
    }

    for entity_type, label in label_map.items():
        for _ in range(per_type):
            entity = spawn_entity(entity_type, sim_time=0.0)
            features = extract_features(entity)
            X.append(features)
            y.append(label)

    return np.array(X), np.array(y)


# ── Classifier ────────────────────────────────────────────────────────────────

class ThreatClassifier:
    """
    Wraps a RandomForestClassifier with SENTINEL-specific scoring logic.
    Outputs threat_score, confidence, and feature importances.
    """

    def __init__(self):
        self.model = RandomForestClassifier(
            n_estimators=100,
            max_depth=8,
            min_samples_leaf=5,
            random_state=42,
        )
        self.trained = False

    def train(self, n_samples: int = 2000, verbose: bool = True):
        """
        Generate synthetic training data and fit the classifier.
        Prints a classification report so we can see how well it separates types.
        """
        if verbose:
            print(f"Generating {n_samples} synthetic training samples...")

        X, y = generate_training_data(n_samples)
        X_train, X_test, y_train, y_test = train_test_split(
            X, y, test_size=0.2, random_state=42, stratify=y
        )

        self.model.fit(X_train, y_train)
        self.trained = True

        if verbose:
            y_pred = self.model.predict(X_test)
            print("\nClassifier Training Complete")
            print("="*40)
            print(classification_report(
                y_test, y_pred,
                target_names=["non-threat", "hostile", "ambiguous"]
            ))

    def score(self, entity: Entity) -> dict:
        """
        Score a single entity and return:
        - threat_score   : float 0.0 → 1.0 (probability of being hostile)
        - confidence     : float 0.0 → 1.0 (how certain the model is)
        - label          : string classification ("non-threat" | "hostile" | "ambiguous")
        - feature_importance : dict mapping feature names to their importance scores
        """
        if not self.trained:
            raise RuntimeError("Classifier must be trained before scoring")

        features     = extract_features(entity).reshape(1, -1)
        probabilities = self.model.predict_proba(features)[0]   # [p_nonthreat, p_hostile, p_ambiguous]
        predicted_class = self.model.predict(features)[0]

        # threat_score is the probability of being hostile
        threat_score = float(probabilities[1])

        # Confidence is how far the top probability is from uniform (0.33 for 3 classes)
        # High confidence = model strongly leans one way
        top_prob   = float(max(probabilities))
        confidence = round((top_prob - (1/3)) / (1 - (1/3)), 3)
        confidence = max(0.0, min(1.0, confidence))  # Clamp to [0, 1]

        label_map  = {0: "non-threat", 1: "hostile", 2: "ambiguous"}
        label      = label_map.get(predicted_class, "unknown")

        # Feature importances from the forest — shows what drove the score
        importances = {
            name: round(float(imp), 4)
            for name, imp in zip(FEATURE_NAMES, self.model.feature_importances_)
        }

        return {
            "threat_score":        round(threat_score, 3),
            "confidence":          confidence,
            "label":               label,
            "probabilities": {
                "non_threat": round(float(probabilities[0]), 3),
                "hostile":    round(float(probabilities[1]), 3),
                "ambiguous":  round(float(probabilities[2]), 3),
            },
            "feature_importance":  importances,
        }


# ── Global classifier instance ────────────────────────────────────────────────
# Trained once at server startup and reused for all scoring requests.

classifier = ThreatClassifier()


def train_classifier():
    """Called at FastAPI startup to train the classifier before serving requests."""
    classifier.train(n_samples=2000, verbose=True)